### PR TITLE
arm32: support arm32 so that library works on raspberry pi

### LINKED ISSUE #13: ARM support
```
  File "/home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/revChatGPT/revChatGPT.py", line 4, in <module>
    import tls_client
  File "/home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/tls_client/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kot/.asdf/installs/python/3.11.0/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kot/.asdf/installs/python/3.11.0/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/kot/.local/share/virtualenvs/chatGPT-discord-bot-BNM29DVl/lib/python3.11/site-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory
```
`arch` is `aarch64`, `amd64` will not work here.

### PR DESCRIPTION
**Pull request by Kidsan**
This adds support for raspberry pi
Resolves #13

### CODE REVIEW

**Comment by xie-xuan** [comment]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x44 pc=0x7569467c]

goroutine 17 [running, locked to thread]:
github.com/bogdanfinn/tls-client.(*httpClient).Do(0x44926270, 0x4495a280)
        /home/pi/tls_client/client.go:209 +0x30
main.request(0x752388)
        /home/pi/tls_client/cffi_dist/main.go:146 +0x254`
I tried to apply the modification of this branch on Raspberry Pi 3B+, but there still seems to be a problem,  from the go file.

**Comment by Kidsan** [comment]
@xie-xuan thanks for testing it. Can you link me a runnable example go program that I can use to test it?

**Comment by xie-xuan** [comment]
[https://github.com/bogdanfinn/tls-client](url)
Can't upload files here.
I compile on raspberry pi with this project.
`echo "Build linux armv7"`
`GOOS=linux CGO_ENABLED=1 GOARCH=arm GOARM=7 CC="gcc" go build -buildmode=c-shared -o ./dist/tls-client-arm32.so`
build.sh adds configuration options for linux arm, and annotates cross-compilation options for other architectures.
It should also be possible to configure the go environment to cross-compile armv7 programs on other architectures.

**Comment by acheong08** [comment]
@xie-xuan Do you mind uploading it onto GitHub? I will try to add it to my fork

**Comment by xie-xuan** [comment]
> @xie-xuan Do you mind uploading it onto GitHub? I will try to add it to my fork

Glad to be able to provide you with a solution.
My method is the same as this.[https://github.com/acheong08/ChatGPT/issues/162#issuecomment-1344419445]()
No modifications were made to chatGPT.Let Python-Tls-Client add support for arm32 by manually adding files. The solution to the fundamental problem still requires Python-Tls-Client to increase support for multiple architectures.

**Comment by ElementQi** [comment]
It run successfully on 3B. Thanks a lot.

**Comment by LovanDog** [comment]
AttributeError: /usr/local/lib/python3.9/dist-packages/tls_client-0.2.1-py3.9.egg/tls_client/dependencies/tls-client-arm32.so: undefined symbol: freeMemory

**Comment by reiven** [comment]
Hi! i have the same issue here @Kidsan 
`tls-client-amd64.so: undefined symbol: freeMemory`

**Pull request closed without merging**
